### ISSUE TITLE
Assert in vkGetInstanceProcAddr

### ISSUE THREAD

**Issue by ilkkasaa** [google/gf-layers#16]
I was running the Amber scoop layer with Validation layers on. Everything is working fine when I define `VK_INSTANCE_LAYERS=VK_LAYER_KHRONOS_validation:VkLayer_GF_amber_scoop` but reversing the layer order causes assert here: https://github.com/google/gf-layers/blob/aa904ec6869b4b8bdf02f667c4e481260e395059/src/VkLayer_GF_amber_scoop/src/amber_scoop_layer.cc#L471

I think we should simply set our dispatch table's `vkGetInstanceProcAddr` pointer to be `next_get_instance_proc_address` instead of calling `next_get_instance_proc_address(*pInstance, "vkGetInstanceProcAddr")` .

At least looking at the loader's dispatch table helper it's implemented that way: https://github.com/KhronosGroup/Vulkan-Loader/blob/e2b55419a3708880026f84eef10a0ad601d2776b/loader/generated/vk_dispatch_table_helper.h#L917

Same applies also to `vkGetDeviceProcAddr`.

**Comment by paulthomson** [comment]
Yes, sounds good to me. Thanks for investigating. There is definitely some confusion about this (and I heard about some weird bugs that relate to where you are allowed to use the get proc address function) so I obtained the function like this and added the assertion to see if it would ever fail. But indeed I think your suggestion must be correct.
